// Generated by render.py from KEEPERS in check.py. NONE of these may be flagged.

const MUSH = 0.60; // measured floor of the destroyed case; don't lower

// must run before flush() because the buffer is reused
doThing();

/** Returns null when the layer has no mask. @param l layer */
export function getMask(l) {}

// swallow: upstream 404s are expected here, see WEB-2988
} catch {}

// Lifecycle (cleanup-on-item-removal) is owned by ImageAnalysisService
code();

// the centre offset is
// reliable (rotation and a sign-only scale both fix it). Works
code();

// we disarm on tool
// switch. Keyed on the RESOLVED store identity, not activeTool()
code();

// three
// paths (ESC, drawer-state change, re-selecting the same tool) disarm
code();

// problem tracked as WEB-2626; do not "fix" this spec by adding verify()
code();

// intermittently never schedules on Replicate (WEB-2729); making it a
// long-poll instead
code();

// return the in-flight promise without re-snapshotting.
code();

// await later, when the local is long out of scope, so
// the trace id is already gone
code();
