// Generated by render.py from FIXTURES in check.py. Every line here MUST be flagged.

// ===== HELPERS =====
code();

// loop over items
for (const i of items) {}

/** Gets the user. */
function getUser() {}

// const x = foo();
real();

// added for WEB-1234
code();

// WEB-2932 U4: single owner of the Remove-Logo region domain
code();

// R2 (Logo Removal v2, WEB-2845) / FD5 (WEB-2896, U5): the box-crosshair
code();

// Pure geometry for the canvas overlays that track a MEDIA layer (WEB-2957).
code();
