#!/usr/bin/env python3
"""Render the .ts fixtures from check.py's inline FIXTURES/KEEPERS lists.

The fixtures used to be hand-mirrored copies that said "Mirrors FIXTURES in
check.py" while nothing checked it, and they had drifted. Generating them keeps
one source of truth and still exercises the file-walking path, which the
tempfile-based self-test never touches.

  render.py           # write the fixture files
  render.py --check   # print nothing and exit 0 when they match, diff and 1 when not
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CHECK = HERE.parent / 'check.py'

HEADER = {
    'known-bad.ts': '// Generated by render.py from FIXTURES in check.py. Every line here MUST be flagged.',
    'keepers.ts': '// Generated by render.py from KEEPERS in check.py. NONE of these may be flagged.',
}


def lists():
    spec = importlib.util.spec_from_file_location('comment_cut_check', CHECK)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return [c[0] for c in mod.FIXTURES], list(mod.KEEPERS)


def render(name, cases):
    return '\n\n'.join([HEADER[name]] + [c.rstrip('\n') for c in cases]) + '\n'


def main():
    fixtures, keepers = lists()
    want = {'known-bad.ts': render('known-bad.ts', fixtures),
            'keepers.ts': render('keepers.ts', keepers)}
    if '--check' in sys.argv:
        bad = 0
        for name, text in want.items():
            have = (HERE / name).read_text() if (HERE / name).exists() else ''
            if have != text:
                print(f'{name}: does not match check.py\'s inline list; run render.py')
                bad = 1
        return bad
    for name, text in want.items():
        (HERE / name).write_text(text)
        print(f'wrote {name}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
