#!/usr/bin/env bash
# claude-modes V2 (U7 / R22 wedge recovery).
#
# Use case:
#   The user manually edited ~/.claude/modes/_global.yaml and removed
#   the claude-modes@<marketplace> entry from enabledPlugins, then ran
#   /mode:set + /reload-plugins. claude-modes is now disabled in Claude
#   Code's plugin set; /mode:set commands no longer work because the
#   plugin's slash commands are gone. They need a way to re-enable
#   claude-modes WITHOUT invoking the plugin itself.
#
# Invocation:
#   Run OUTSIDE Claude Code:
#     bash ~/.claude/plugins/claude-modes/scripts/restore-claude-modes.sh
#
# Behavior:
#   - Verifies _global.yaml exists (otherwise → tell user to run setup).
#   - Reads _global.yaml via yaml.safe_load (Python-pinned).
#   - If any mechanism.enabledPlugins key starts with "claude-modes@" and
#     is true → exit 0 (already enabled, no action needed).
#   - Otherwise adds "claude-modes@local-dev: true" (synthetic identifier
#     consistent with setup.sh's R22 enforcement) and writes back via
#     the SAME atomic born-at-0600 idiom (umask 077 + mktemp + write +
#     mv). We DO NOT source write-mode-yaml.sh here — wedge recovery
#     must work even when the plugin's other libs may be in an unknown
#     state. Inline implementation only.
#
# Why claude-modes@local-dev not the canonical marketplace name:
#   This script runs pre-publication. Post-publication the script may
#   be updated to write the canonical name; until then, local-dev is
#   the safe synthetic value, identical to setup.sh's default.

set -uo pipefail

CLAUDE_MODES_PYTHON3="${CLAUDE_MODES_PYTHON3:-/usr/bin/python3}"

GLOBAL_YAML="${HOME}/.claude/modes/_global.yaml"

_log() { printf 'restore-claude-modes: %s\n' "$1"; }
_err() { printf 'restore-claude-modes: %s\n' "$1" >&2; }

# ──────────────────────────────────────────────────────────────────────
# Step 1: presence check.
if [ ! -f "$GLOBAL_YAML" ]; then
  _err "claude-modes not installed (no ${GLOBAL_YAML})"
  _err "Run /mode:setup or bash ~/.claude/plugins/claude-modes/scripts/setup.sh first."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────
# Step 2: read _global.yaml + check whether claude-modes is already enabled.
#
# We let Python do the work in two stages so the bash code stays simple
# and the Python body never shell-interpolates user-controlled strings
# (sec-001 / sys.argv pattern).
ALREADY_ENABLED=$("$CLAUDE_MODES_PYTHON3" - "$GLOBAL_YAML" <<'PYEOF' 2>/dev/null
import sys, yaml
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f) or {}
except Exception as e:
    sys.stderr.write(f"could not parse YAML: {e}\n")
    sys.exit(2)
mech = data.get("mechanism") or {}
ep = mech.get("enabledPlugins") or {}
enabled = any(
    isinstance(k, str)
    and k.split("@", 1)[0] == "claude-modes"
    and bool(v)
    for k, v in ep.items()
)
print("1" if enabled else "0")
PYEOF
)
PARSE_RC=$?

if [ "$PARSE_RC" -ne 0 ]; then
  _err "could not parse ${GLOBAL_YAML} (yaml.safe_load failed)"
  _err "Fix the file manually or restore from backup."
  exit 1
fi

if [ "$ALREADY_ENABLED" = "1" ]; then
  _log "claude-modes already enabled in ${GLOBAL_YAML}; no action needed."
  exit 0
fi

# ──────────────────────────────────────────────────────────────────────
# Step 3: synthesize a new YAML body with claude-modes@local-dev: true
# added. We use ruamel-style preservation only if available, but the
# canonical fallback is yaml.safe_dump (acceptable: _global.yaml is
# plugin-generated; round-tripping through safe_dump preserves keys and
# values though comments are dropped). Comments in the file are
# already auto-generated by setup.sh; the regen is acceptable.
NEW_CONTENT=$("$CLAUDE_MODES_PYTHON3" - "$GLOBAL_YAML" <<'PYEOF' 2>/dev/null
import sys, yaml, datetime
path = sys.argv[1]
with open(path) as f:
    data = yaml.safe_load(f) or {}

# Ensure structure exists.
mech = data.setdefault("mechanism", {})
ep = mech.setdefault("enabledPlugins", {})

# Add the synthetic identifier (R22 enforcement marker).
ep["claude-modes@local-dev"] = True

# Re-sort enabledPlugins for deterministic output.
mech["enabledPlugins"] = dict(sorted(ep.items()))

# Refresh description with a recovery footnote so the user can see
# when this was re-enabled and by what mechanism.
ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
existing_desc = data.get("description") or ""
suffix = f"\n[restore-claude-modes.sh re-added claude-modes@local-dev at {ts}]\n"
if "restore-claude-modes.sh re-added" not in existing_desc:
    data["description"] = (existing_desc.rstrip() + suffix) if existing_desc else suffix

print(yaml.safe_dump(data, default_flow_style=False, sort_keys=False), end="")
PYEOF
)
GEN_RC=$?

if [ "$GEN_RC" -ne 0 ] || [ -z "$NEW_CONTENT" ]; then
  _err "could not generate updated YAML content"
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────
# Step 4: atomic born-at-0600 write (inline; do NOT source write-mode-yaml.sh).
target_dir="$(dirname "$GLOBAL_YAML")"
if [ ! -d "$target_dir" ]; then
  _err "directory ${target_dir} missing — refusing to create here (run /mode:setup instead)"
  exit 1
fi

tmp=$( (umask 077 && mktemp "${target_dir}/.restore-claude-modes.XXXXXX") ) || {
  _err "mktemp failed in ${target_dir}"
  exit 1
}
# shellcheck disable=SC2064
trap "rm -f '${tmp}'" EXIT

printf '%s' "$NEW_CONTENT" > "$tmp" || {
  _err "could not write tmp file ${tmp}"
  exit 1
}

if ! mv "$tmp" "$GLOBAL_YAML"; then
  _err "atomic mv ${tmp} → ${GLOBAL_YAML} failed"
  exit 1
fi
trap - EXIT

if [ ! -L "$GLOBAL_YAML" ]; then
  chmod 0600 "$GLOBAL_YAML" 2>/dev/null || true
fi

_log "Re-enabled claude-modes@local-dev in ${GLOBAL_YAML}. Run /mode:setup or /reload-plugins to apply."
exit 0
