#!/bin/bash

# ClawCrush — Register zombie crusher with que-do scheduler
#
# Creates a custom script runner (not a Claude prompt task) since
# crush.sh is a pure bash scanner that doesn't need Claude.
#
# Usage: setup-quedo.sh [--remove]

set -euo pipefail

JOB_NAME="clawcrush"
QUEUE_DIR="$HOME/.slate-queue"
SCRIPT_DIR="$QUEUE_DIR/scripts"
STATE_DIR="$QUEUE_DIR/state/$JOB_NAME"
JOBS_DIR="$QUEUE_DIR/jobs"
PLIST_PATH="$HOME/Library/LaunchAgents/com.slate.${JOB_NAME}.plist"

# Resolve the plugin root (directory containing this script's parent)
PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── Remove mode ────────────────────────────────

if [[ "${1:-}" == "--remove" ]]; then
  echo "Removing ClawCrush from que-do..."

  # Unload LaunchAgent
  launchctl bootout "gui/$(id -u)/com.slate.${JOB_NAME}" 2>/dev/null || \
    launchctl unload "$PLIST_PATH" 2>/dev/null || true

  # Remove files
  rm -f "$SCRIPT_DIR/${JOB_NAME}.sh"
  rm -f "$JOBS_DIR/slate-${JOB_NAME}"
  rm -f "$PLIST_PATH"

  # Remove from manifest
  if [[ -f "$QUEUE_DIR/manifest" ]]; then
    grep -v "^${JOB_NAME}|" "$QUEUE_DIR/manifest" > "$QUEUE_DIR/manifest.tmp" 2>/dev/null || true
    mv "$QUEUE_DIR/manifest.tmp" "$QUEUE_DIR/manifest"
  fi

  echo "{\"status\":\"removed\"}"
  exit 0
fi

# ── Check prerequisites ───────────────────────

if [[ ! -d "$QUEUE_DIR" || ! -f "$QUEUE_DIR/queue.sh" ]]; then
  echo "{\"status\":\"error\",\"message\":\"que-do not found at $QUEUE_DIR\"}" >&2
  exit 1
fi

# ── Create directories ─────────────────────────

mkdir -p "$SCRIPT_DIR" "$STATE_DIR/logs" "$JOBS_DIR"

# ── Ensure boilerplate exists ──────────────────

if [[ ! -f "$QUEUE_DIR/lib/boilerplate.sh" ]]; then
  echo "{\"status\":\"error\",\"message\":\"que-do boilerplate.sh not found\"}" >&2
  exit 1
fi

# ── Generate runner script ─────────────────────

cat > "$SCRIPT_DIR/${JOB_NAME}.sh" <<'RUNNER'
#!/bin/bash
# GENERATED BY: ClawCrush plugin
# TYPE: custom script (no Claude needed)
JOB_NAME="clawcrush"
WORKING_DIR="$HOME"
PERIOD_FORMAT=""
STATE_DIR="${HOME}/.slate-queue/state/${JOB_NAME}"
LOG_DIR="${STATE_DIR}/logs"

FAILURE_TRACKER="${STATE_DIR}/.failures.json"
MAX_RETRIES_PER_PERIOD=3
TOTAL_TIMEOUT=120
STALL_TIMEOUT=60

source ~/.slate-queue/lib/boilerplate.sh

main() {
  log "ClawCrush: starting zombie scan"

  # Find the crush.sh script (resolve from runner location)
  local crush_script
  crush_script="$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")/../scripts/crush.sh"

  # Fallback: look in plugin directory
  if [[ ! -f "$crush_script" ]]; then
    # Search for clawcrush plugin
    for dir in "$HOME/.claude/plugins/clawcrush" "$HOME/.claude/plugins/"*/; do
      if [[ -f "${dir}/scripts/crush.sh" ]]; then
        crush_script="${dir}/scripts/crush.sh"
        break
      fi
    done
  fi

  if [[ ! -f "$crush_script" ]]; then
    log "ERROR: crush.sh not found"
    return 1
  fi

  # Run the cron mode (silent auto-kill)
  bash "$crush_script" cron 2>&1
  local exit_code=$?

  if [[ $exit_code -eq 0 ]]; then
    log "ClawCrush: zombie scan complete"
  else
    log "ClawCrush: scan failed with exit code $exit_code"
  fi

  return $exit_code
}

# ── Entry point ──────────────────────────────

acquire_lock || { log "Already running, skipping"; exit 0; }
rotate_logs 14

main
RUNNER

chmod +x "$SCRIPT_DIR/${JOB_NAME}.sh"

# Syntax check
if ! bash -n "$SCRIPT_DIR/${JOB_NAME}.sh" 2>/dev/null; then
  echo "{\"status\":\"error\",\"message\":\"Runner script has syntax errors\"}" >&2
  exit 1
fi

# ── Generate wrapper script ───────────────────

cat > "$JOBS_DIR/slate-${JOB_NAME}" <<WRAPPER
#!/bin/bash
export PATH="\${HOME}/.local/bin:/opt/homebrew/bin:/usr/local/bin:\${PATH}"
unset CLAUDECODE
exec "${QUEUE_DIR}/queue.sh" \\
  --job ${JOB_NAME} --scheduled \\
  -- ${SCRIPT_DIR}/${JOB_NAME}.sh
WRAPPER

chmod +x "$JOBS_DIR/slate-${JOB_NAME}"

# ── Generate LaunchAgent plist ─────────────────

cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.slate.${JOB_NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${JOBS_DIR}/slate-${JOB_NAME}</string>
    </array>
    <key>StartInterval</key>
    <integer>3600</integer>
    <key>StandardOutPath</key>
    <string>${STATE_DIR}/logs/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>${STATE_DIR}/logs/launchd.log</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

# ── Add to manifest ───────────────────────────

if [[ -f "$QUEUE_DIR/manifest" ]]; then
  # Remove existing entry if present
  grep -v "^${JOB_NAME}|" "$QUEUE_DIR/manifest" > "$QUEUE_DIR/manifest.tmp" 2>/dev/null || true
  mv "$QUEUE_DIR/manifest.tmp" "$QUEUE_DIR/manifest"
fi
echo "${JOB_NAME}|flexible|Hourly zombie process cleanup" >> "$QUEUE_DIR/manifest"

# ── Load LaunchAgent ──────────────────────────

launchctl bootout "gui/$(id -u)/com.slate.${JOB_NAME}" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH" 2>/dev/null || \
  launchctl load "$PLIST_PATH" 2>/dev/null || true

# ── Verify ─────────────────────────────────────

if launchctl print "gui/$(id -u)/com.slate.${JOB_NAME}" &>/dev/null; then
  echo "{\"status\":\"installed\",\"method\":\"que-do\",\"job\":\"${JOB_NAME}\",\"interval\":3600,\"flexibility\":\"flexible\",\"manifest\":\"${QUEUE_DIR}/manifest\"}"
else
  echo "{\"status\":\"warning\",\"message\":\"Files created but LaunchAgent may not have loaded. Check with: launchctl list | grep clawcrush\"}"
fi
